language:
  - php
php:
  - 7.3
  - 7.4
os: linux

before_script:
  - composer install
  - cp .env.example .env
  - php artisan key: generate
  - php artisan jwt: secret


script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)